#!/bin/bash
r="\033[31;1m"
y="\033[33;1m"
yl="\033[1;33m"
g="\033[0;32m"
gl="\033[32;1m"
b="\033[0;36m"
bl="\033[36;1m"
c="\033[36;1m"
p="\033[0;35m"
o="\033[0m"

clear
echo -e "\033[31;1mWARNING :\033[33;1m Tidak Untuk di\033[36;1m Perjual Belikan"
echo -e "\033[0;35m╔═══════════════════════════════════════╗"
echo -e "\033[33;1m║\033[31;1mCODEDBY             :         \033[33;1mJAUNK    ║"
echo -e "\033[33;1m║\033[33;1mYOUTUBE             :         \033[31;1mJAUNK    ║"
echo -e "\033[33;1m║\033[31;1mFACEBOOK            :         \033[33;1mZAUNK    ║"
echo -e "\033[33;1m║\033[33;1mRECODE              :         \033[31;1mSAMPAH!  ║"
echo -e "\033[33;1m╚═══════════════════════════════════════╝"

echo '
[1] spam-call
[2] Exit
'
echo
read -p 'masukan pilihan :' pil
if [[ $pil == 1 ]]; then
read -p 'masukan nomor target :' nomor
link="https://id.jagreward.com/member/verify-mobile/$nomor"
sip="curl -s $link"
sleep 0.2
elif [[ $pil == '2' ]]; then
clear
echo -e "\033[33;1mTERIMAKASIH \033[0;35mGOODBYE"
exit
fi;